### ISSUE TITLE
PHP warning after backend login (rename() function)

### ISSUE THREAD

**Issue by dmnkhhn** [nitsan-technologies/ns_license#4]
Hello,

we keep getting a warning after backend login:
`PHP Warning: rename(): The first argument to copy() function cannot be a directory in /var/www/html/web/typo3conf/ext/ns_license/Classes/Controller/NsLicenseModuleController.php line 280`

The login isn't successful but the warning is gone after a second login.

This happens on the latest TYPO3 version 11 with all nitsan extensions on the latest version.
We are using PHP 8.1 - maybe that's the reason for this warning.

**Comment by nitsan-technologies** [comment]
Hey @dmnkhhn 

Thanks for your valuable feedback. EXT:ns_license is supporting from TYPO3 v8 to v11 with multiple PHP version compatibility. With your test case, We have resolved and released v1.8.6. Please update it https://github.com/nitsan-technologies/ns_license/releases/tag/1.8.6

Cheers, Team NITSAN
