### ISSUE TITLE
PHP Runtime Deprecation Notice in PHP 8.2

### ISSUE THREAD

**Issue by timdreier** [nitsan-technologies/ns_license#5]
With PHP 8.2 the extension throws a deprecation message when trying to login into the TYPO3 backend:

PHP Runtime Deprecation Notice: Creation of dynamic property NITSAN\NsLicense\Hooks\BackendUserLogin::$nsLicenseModule is deprecated in /app/web/public/typo3conf/ext/ns_license/Classes/Hooks/BackendUserLogin.php line 17

**Comment by nitsan-technologies** [comment]
Hey @timdreier 

Thanks for your feedback to keep improving our product. We already plan to make compatibility with TYPO3 v12 + PHP 8.x. We will mostly make this happen around the TYPO3 LTS version release. Thanks for your patience and support.

Cheers, Support Team @T3Planet

**Comment by nitsan-technologies** [comment]
Hey @timdreier 

FYI. We have released new version with fixing PHP deprecation notice https://github.com/nitsan-technologies/ns_license/releases/tag/12.0.0

Cheers!
